# dataset
dataset: Huatuo
tokenize: qwen
not_download: true
entity_file: entity2id_normalized_continuous.json
kg_file: kg_simplified_Coincide_normalized_continuous.csv
# dataloader
context_truncate: 1024
response_truncate: 1024
max_seq_len: 1024
scale: 1
# model
model: KBRD_Qwen
model_path: H:\ThesisCode\model\qwen
token_emb_dim: 300
n_relation: 56
kg_emb_dim: 128
num_bases: 8
n_heads: 2
n_layers: 2
ffn_size: 300
dropout: 0.1
attention_dropout: 0.0
relu_dropout: 0.1
learn_positional_embeddings: false
embeddings_scale: true
reduction: false
n_positions: 1024
user_proj_dim: 512
# optim
rec:
  epoch: 3
  batch_size: 3
  early_stop: True
  stop_mode: max
  patience: 3
  optimizer:
    name: Adam
    lr: !!float 3e-3
conv:
  epoch: 3
  batch_size: 10
  early_stop: True
  stop_mode: min
  optimizer:
    name: Adam
    lr: !!float 1e-3
  lr_scheduler:
    name: ReduceLROnPlateau
    patience: 3
    factor: 0.5

