# dataset
dataset: Huatuo
tokenize: pkuseg
not_download: true
entity_file: entity2id_normalized_continuous.json
kg_file: kg_simplified_Coincide_normalized_continuous.csv
# dataloader
context_truncate: 1024
response_truncate: 1024
scale: 1
# model
model: KBRD
token_emb_dim: 300
n_relation: 56
kg_emb_dim: 128
num_bases: 8
n_heads: 2
n_layers: 2
ffn_size: 300
dropout: 0.1
attention_dropout: 0.0
relu_dropout: 0.1
learn_positional_embeddings: false
embeddings_scale: true
reduction: false
n_positions: 1024
user_proj_dim: 512
shutdown: true
# optim
rec:
  epoch: 50
  batch_size: 128
  early_stop: True
  stop_mode: min
  impatience: 8
  optimizer:
    name: AdamW
    lr: !!float 1e-3
conv:
  epoch: 80
  batch_size: 64
  early_stop: True
  stop_mode: min
  optimizer:
    name: AdamW
    lr: !!float 1e-3
  lr_scheduler:
    name: ReduceLROnPlateau
    patience: 3
    factor: 0.5