# dataset
dataset: Huatuo
tokenize: qwen
not_download: true
entity_file: entity2id_normalized_continuous.json
kg_file: kg_simplified_Coincide_normalized_continuous.csv
# dataloader
context_truncate: 2048
response_truncate: 2048
use_chatML: true
max_seq_len: 2048
scale: 1
# model
model: KBRD_Qwen
use_qwen: true
model_path: /hy-tmp/qwen2.5-1.5B-Instruct
token_emb_dim: 300
use_rgcn: true
num_rgcn_layers: 1
n_relation: 2
kg_emb_dim: 512
mlp_hidden_dim: 512
num_bases: 8
user_proj_dim: 512
conv_system_template: 你是一个专业的AI医疗助手。你的任务是模拟在线问诊过程，与用户进行中文对话。请仔细理解用户描述的症状。如果信息不足以做出判断，你需要主动提出针对性的问题，以获取更详细的症状信息、病史或相关情况。在收集足够信息后，根据对话内容，提供可能的健康状况分析或初步医疗建议。

# optim
seed: 3402
rec:
  epoch: 200
  batch_size: 256
  num_neg_samples: 0
  early_stop: true
  stop_mode: min
  impatience: 8
  optimizer:
    name: AdamW
    lr: !!float 1e-3
conv:
  epoch: 50
  batch_size: 1
  early_stop: True
  stop_mode: min
  optimizer:
    name: AdamW
    lr: !!float 2e-6
  lr_scheduler:
    name: ReduceLROnPlateau
    patience: 5
    factor: 0.5